// Constants shared by ndoe scripts and frontend
export const GEOJSON_ABS_PATH = '/Users/erik/Work/eu-trees4f/out/geojson'
export const EUTREES4F_DATASET_ABS_PATH =
  '/Users/erik/Work/eu-trees4f/in/EU-Trees4F_dataset/ens_sdms'
export const SPECIES = './out/species.json'
export const SPECIES_DETAIL = './src/species_detail.json'
export const QGIS_BATCH = './out/qgis/batch.json'
export const PBF = './out/pbf'
export const IN = 'in'
export const GEOJSON = 'out/geojson'
export const BASEMAP_COUNTRIES = 'basemap_countries'
export const BASEMAP_COUNTRIES_SRC = 'gadm_countries.geojson'
export const BASEMAP_REGIONS = 'basemap_regions'
export const BASEMAP_REGIONS_SRC = 'gadm_regions_custom.geojson'
export const RCP = '85'
export const SPECIES_WHITELIST = [
  'Abies_alba',
  'Acer_campestre',
  'Acer_opalus',
  'Acer_platanoides',
  'Acer_pseudoplatanus',
  'Alnus_glutinosa',
  'Alnus_incana',
  'Arbutus_unedo',
  'Aria_edulis',
  'Betula_pendula',
  'Betula_pubescens',
  'Borkhausenia_intermedia',
  'Carpinus_betulus',
  'Carpinus_orientalis',
  'Castanea_sativa',
  'Celtis_australis',
  'Ceratonia_siliqua',
  'Cormus_domestica',
  'Corylus_avellana',
  'Cupressus_sempervirens',
  'Fagus_sylvatica',
  'Fraxinus_angustifolia',
  'Fraxinus_excelsior',
  'Fraxinus_ornus',
  'Juglans_regia',
  'Juniperus_thurifera',
  'Larix_decidua',
  'Laurus_nobilis',
  'Malus_sylvestris',
  'Olea_europaea',
  'Ostrya_carpinifolia',
  'Picea_abies',
  'Pinus_brutia',
  'Pinus_cembra',
  'Pinus_halepensis',
  'Pinus_nigra',
  'Pinus_pinaster',
  'Pinus_pinea',
  'Pinus_sylvestris',
  'Pistacia_lentiscus',
  'Pistacia_terebinthus',
  'Populus_alba',
  'Populus_nigra',
  'Populus_tremula',
  'Prunus_avium',
  'Prunus_padus',
  'Pyrus_communis',
  'Quercus_cerris',
  'Quercus_coccifera',
  'Quercus_faginea',
  'Quercus_frainetto',
  'Quercus_ilex',
  'Quercus_petraea',
  'Quercus_pubescens',
  'Quercus_pyrenaica',
  'Quercus_robur',
  'Quercus_suber',
  'Robinia_pseudoacacia',
  'Salix_alba',
  'Sorbus_aucuparia',
  'Taxus_baccata',
  'Tilia_cordata',
  'Tilia_platyphyllos',
  'Torminalis_glaberrima',
  'Ulmus_glabra',
  'Ulmus_laevis',
  'Ulmus_minor',
]
export const GRIDS = [
  { res: 80000, minZoom: 0, maxZoom: 1 },
  { res: 40000, minZoom: 2, maxZoom: 3 },
  { res: 20000, minZoom: 4, maxZoom: 5 },
  { res: 10000, minZoom: 6, maxZoom: 8 },
]

// < 100 000km2
export const COUNTRIES_WITHOUT_REGIONS = [
  'Hungary',
  'Portugal',
  'Serbia',
  'Austria',
  'Czechia',
  'Ireland',
  'Lithuania',
  'Latvia',
  'Croatia',
  'Bosnia and Herzegovina',
  'Slovakia',
  'Estonia',
  'Denmark',
  'Switzerland',
  'Netherlands',
  'Moldova',
  'Belgium',
  'Albania',
  'North Macedonia',
  'Turkey',
  'Slovenia',
  'Montenegro',
  'Kosovo',
  'Azerbaijan',
  'Georgia',
  'Luxembourg',
  'Andorra',
  'Malta',
  'Liechtenstein',
]
